# This file was generated by GoReleaser. DO NOT EDIT.
cask "llmkube" do
  version "0.8.20"

  on_macos do
    on_intel do
      sha256 "41861915589fdaa0463e6ae08635caae7cd0fc7f51d60d84ecc6b6e68c0c4c06"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "df910b6b07076314bd4d3ebc4be8bd83f185425a9f06677881c654244105109b"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0441d800ea3139a0ade9170972f05e608703adb6d7670dd7fb1ff6b73bf53a4"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "80ea2931defcc6e2a02a0a385b03fc42c0bcf614ddbee289ab59e1f45672a0a4"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_linux_arm64.tar.gz"
    end
  end

  name "llmkube"
  desc "GPU-accelerated Kubernetes operator for local LLM inference"
  homepage "https://github.com/defilantech/LLMKube"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llmkube"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llmkube"]
    end
  end

  # No zap stanza required

end
