# This file was generated by GoReleaser. DO NOT EDIT.
cask "llmkube" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "8b0b3c411245c3f30e179898fb9560071580f827172e8ea85a2b7dadd9db6326"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13c1079e340b2aa61bd71f676b40c59e06f2fd30a366abe1878863f20fdb3c15"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1855f8a7129508bc177fc727077b7ac8c108fd7321a8d39c204f307f257c816d"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc25729896232c01db5811a8af84fe9cce93333c6b3dd382809d1137af23bbbe"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_linux_arm64.tar.gz"
    end
  end

  name "llmkube"
  desc "GPU-accelerated Kubernetes operator for local LLM inference"
  homepage "https://github.com/defilantech/LLMKube"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llmkube"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llmkube"]
    end
  end

  # No zap stanza required

end
