# This file was generated by GoReleaser. DO NOT EDIT.
cask "llmkube" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "8971d4e43b97483c69c55619131e44a8456b3d5e1e950e9c038f4df68dfd0f76"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc3413e3779a2e41a1700ebc0af3a780d70c38ff48c61415f27ab51ffd26ca04"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc5cbb7d8ad4241cfe5bebda7da7436c6caa35c7ffb879cc0c1ff6f7fc674b84"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3111c7bae4d8151c69718fab5c65cd04b93dd3e04d32475c45a3a70f11c8ca16"
      url "https://github.com/defilantech/LLMKube/releases/download/v#{version}/LLMKube_#{version}_linux_arm64.tar.gz"
    end
  end

  name "llmkube"
  desc "GPU-accelerated Kubernetes operator for local LLM inference"
  homepage "https://github.com/defilantech/LLMKube"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llmkube"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/llmkube"]
    end
  end

  # No zap stanza required

end
