# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infercost < Formula
  desc "Kubernetes-native cost intelligence for on-premises AI inference"
  homepage "https://infercost.ai"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defilantech/infercost/releases/download/v0.4.0/infercost_0.4.0_darwin_amd64.tar.gz"
      sha256 "5e2895e8bad3ddce0c401010f75cf74df3e46984b0017a16c40c99191343fc47"

      define_method(:install) do
        bin.install "infercost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defilantech/infercost/releases/download/v0.4.0/infercost_0.4.0_darwin_arm64.tar.gz"
      sha256 "7e1f2d476af28b9d3667ae4bb3c82958ba4fdff868cc368577254f26294a3b5b"

      define_method(:install) do
        bin.install "infercost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/infercost/releases/download/v0.4.0/infercost_0.4.0_linux_amd64.tar.gz"
      sha256 "83fbae6372ceae0728c31ed3da935e3a57903e9bb6ef70c9a30ed61a4ae3d0ef"
      define_method(:install) do
        bin.install "infercost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/infercost/releases/download/v0.4.0/infercost_0.4.0_linux_arm64.tar.gz"
      sha256 "08a87e5f6ae4c9df039ad0e70ba4026c8f093a4ef469471f1c23c38e3d10d44f"
      define_method(:install) do
        bin.install "infercost"
      end
    end
  end

  test do
    system "#{bin}/infercost", "version"
  end
end
