# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infercost < Formula
  desc "Kubernetes-native cost intelligence for on-premises AI inference"
  homepage "https://infercost.ai"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defilantech/infercost/releases/download/v0.3.0/infercost_0.3.0_darwin_amd64.tar.gz"
      sha256 "530cff225a7489a0e0dedb9f27457c06182c8917f1350ae7c6de53e4327730d8"

      define_method(:install) do
        bin.install "infercost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defilantech/infercost/releases/download/v0.3.0/infercost_0.3.0_darwin_arm64.tar.gz"
      sha256 "b0c7fd0e823b88c3e03f3426409a83e83bbb3624565a7c8846c2f1fbb1b6a1e7"

      define_method(:install) do
        bin.install "infercost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/infercost/releases/download/v0.3.0/infercost_0.3.0_linux_amd64.tar.gz"
      sha256 "a22b8b824c0ec699b1fa07e713aec3a380ae027bc2172fc12ea3e446dc8cc942"
      define_method(:install) do
        bin.install "infercost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/infercost/releases/download/v0.3.0/infercost_0.3.0_linux_arm64.tar.gz"
      sha256 "289bfbd3d0243301b7c32308426bd2aebd64a4136d5f0f0f77384695aac2c86b"
      define_method(:install) do
        bin.install "infercost"
      end
    end
  end

  test do
    system "#{bin}/infercost", "version"
  end
end
