# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infercost < Formula
  desc "Kubernetes-native cost intelligence for on-premises AI inference"
  homepage "https://infercost.ai"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defilantech/infercost/releases/download/v0.1.1/infercost_0.1.1_darwin_amd64.tar.gz"
      sha256 "c4ee07f901434931e718eedf88d39ee3e68feee05437c87adcd5009d09828761"

      define_method(:install) do
        bin.install "infercost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defilantech/infercost/releases/download/v0.1.1/infercost_0.1.1_darwin_arm64.tar.gz"
      sha256 "72e99732bdf5655a52b8789eeb7b3e955b5efe817a94d896afce7e86168ab948"

      define_method(:install) do
        bin.install "infercost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/infercost/releases/download/v0.1.1/infercost_0.1.1_linux_amd64.tar.gz"
      sha256 "3a86a98423f4613466234109bbf1541f1b8573fb7d4aff687cee4d6e10eb406e"
      define_method(:install) do
        bin.install "infercost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/infercost/releases/download/v0.1.1/infercost_0.1.1_linux_arm64.tar.gz"
      sha256 "bda298cd3c372c121edf47e998103ddbfee3067f9831bad4c68bdcddf422f5a6"
      define_method(:install) do
        bin.install "infercost"
      end
    end
  end

  test do
    system "#{bin}/infercost", "version"
  end
end
