# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llmkube < Formula
  desc "GPU-accelerated Kubernetes operator for local LLM inference"
  homepage "https://github.com/defilantech/LLMKube"
  version "0.7.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defilantech/LLMKube/releases/download/v0.7.12/LLMKube_0.7.12_darwin_amd64.tar.gz"
      sha256 "d53b72c28a5208403d14b13f6a4771e9aef06e06cd6bfff85d165f5d27fd7d04"

      define_method(:install) do
        bin.install "llmkube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defilantech/LLMKube/releases/download/v0.7.12/LLMKube_0.7.12_darwin_arm64.tar.gz"
      sha256 "e91b5e8208963fae037826d851ec3955793b7ca9216ff1088b91f52d5f8ba294"

      define_method(:install) do
        bin.install "llmkube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/LLMKube/releases/download/v0.7.12/LLMKube_0.7.12_linux_amd64.tar.gz"
      sha256 "4f573b305812b7ab449d7bf12157b46e3f42578ac893af5d03c416e1e52ec18c"
      define_method(:install) do
        bin.install "llmkube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/LLMKube/releases/download/v0.7.12/LLMKube_0.7.12_linux_arm64.tar.gz"
      sha256 "ae596989100e02545fed01c2063c39897c8c983b62f78360f7a47b8154de0825"
      define_method(:install) do
        bin.install "llmkube"
      end
    end
  end

  test do
    system "#{bin}/llmkube", "version"
  end
end
