# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llmkube < Formula
  desc "GPU-accelerated Kubernetes operator for local LLM inference"
  homepage "https://github.com/defilantech/LLMKube"
  version "0.8.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defilantech/LLMKube/releases/download/v0.8.13/LLMKube_0.8.13_darwin_amd64.tar.gz"
      sha256 "07bdbca25cde43e1e5b2bf2689eee7fbe20a59c0a0f960021be9a446d056018c"

      define_method(:install) do
        bin.install "llmkube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defilantech/LLMKube/releases/download/v0.8.13/LLMKube_0.8.13_darwin_arm64.tar.gz"
      sha256 "bda3fa94a68b13b68ed335196fcda102ed174746d149c99246a0c639379652de"

      define_method(:install) do
        bin.install "llmkube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/LLMKube/releases/download/v0.8.13/LLMKube_0.8.13_linux_amd64.tar.gz"
      sha256 "25e5c601d4e5d7db7b10fb414fcf952588553a0ca5fa091d0a9fd050b447b26e"
      define_method(:install) do
        bin.install "llmkube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defilantech/LLMKube/releases/download/v0.8.13/LLMKube_0.8.13_linux_arm64.tar.gz"
      sha256 "c30b90a5918f0df92440275dd3a3a0101cfec06976cf131cc22116234ed89493"
      define_method(:install) do
        bin.install "llmkube"
      end
    end
  end

  test do
    system "#{bin}/llmkube", "version"
  end
end
